USE GD2C2022

EXEC GAME_OF_JOINS.Drop_All_Tables

EXEC GAME_OF_JOINS.BI_Drop_All_Tables

EXEC GAME_OF_JOINS.BI_Erase_All_Foreign_Keys

EXEC GAME_OF_JOINS.Erase_All_Foreign_Keys

EXEC GAME_OF_JOINS.BI_Drop_All_Procedures

EXEC GAME_OF_JOINS.Drop_All_Procedures

DROP PROCEDURE GAME_OF_JOINS.Drop_All_Tables

DROP PROCEDURE GAME_OF_JOINS.BI_Drop_All_Tables

DROP PROCEDURE GAME_OF_JOINS.BI_Erase_All_Foreign_Keys

DROP PROCEDURE GAME_OF_JOINS.Erase_All_Foreign_Keys

DROP PROCEDURE GAME_OF_JOINS.BI_Drop_All_Procedures

DROP PROCEDURE GAME_OF_JOINS.Drop_All_Procedures

DROP SCHEMA GAME_OF_JOINS

GO